### ISSUE TITLE
Doesn't work with assets prefix 

### ISSUE THREAD

**Issue by kaknut** [TryGhost/gatsby-plugin-advanced-sitemap#84] opened 2020-07-19 18:59 UTC
Sitemap doesn't gets generated as the plugin fails to find proper path.

Build using : gatsby build --prefix-paths

**Comment by aileen** [comment] 2020-08-03 03:56
Duplicate of https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/issues/13

**Closed by aileen** 2020-08-03 03:56 UTC
