### ISSUE TITLE
Some conflict with siteMetadata query on config file

### ISSUE THREAD

**Issue by anonimoconiglio** [TryGhost/gatsby-plugin-advanced-sitemap#2] opened 2019-03-14 09:13 UTC
During the build process it return me this error:
```json
error Plugin gatsby-plugin-advanced-sitemap returned an error

  Error: Cannot query field "siteUrl" on type "siteMetadata_2".
  GraphQL request (13:7)
  12:     siteMetadata {
  13:       siteUrl
            ^
  14:     }
```

This is my gatsby-config.js: 

```js
module.exports = {
  siteMetadata: {
    title: "Blog Title",
    description: "Blog Description"
  },
  plugins: [
   [... Other_Plugins ... ],
    {
      resolve: `gatsby-plugin-advanced-sitemap`,
      options: {
        // 1 query for each data type
        query: `
            {
              {
                allMarkdownRemark{
                    edges {
                        node {
                            frontmatter {
                                slug
                            }
                        }
                    }
                }
            }
            }`,
        mapping: {
          // Each data type can be mapped to a predefined sitemap
          // Routes can be grouped in one of: posts, tags, authors, pages
	allMarkdownRemark: {
            sitemap: `posts`
          }
        },
        exclude: [
          `/404`
        ],
        createLinkInHead: true
      }
    }
  ]
};
```

Should I insert the query outside the plugins?

**Comment by AileenCGN** [comment] 2019-03-14 09:17
Hey @anonimoconiglio 

You will need to add `siteUrl` to your config:

```js
module.exports = {
  siteMetadata: {
    title: "Blog Title",
    description: "Blog Description",
    siteUrl: "<your URL goes here>" // that's the one missing
  },
  plugins: [
    ...
  ]
```

`siteUrl` is a required property in `siteMetadata` in order to use this plugin. 

Hope that helps!

Gonna close this issue, as it's not a bug 🐛

**Closed by AileenCGN** 2019-03-14 09:17 UTC

**Comment by anonimoconiglio** [comment] 2019-03-14 11:17
Thanks! It worked (sorry for the noobness)

**Comment by AileenCGN** [comment] 2019-03-15 02:26
Perfect 👌
