### ISSUE TITLE
runner.query(...).then is not a function

### ISSUE THREAD

**Issue by tobinharris** [TryGhost/gatsby-plugin-advanced-sitemap#15] opened 2020-01-28 21:42 UTC
### Issue Summary

`yarn build` is failing with error:

`runner.query(...).then is not a function` 

### To Reproduce

1. See config below
2. `yarn build`
3. Fail

I'd expect it to work, but get this:

```
- graphql-runner.js:11 
    [pocketworks-web]/[gatsby]/dist/bootstrap/graphql-runner.js:11:59
  
  - gatsby-node.js:190 runQuery
    [pocketworks-web]/[gatsby-plugin-advanced-sitemap]/gatsby-node.js:190:10
  
  - gatsby-node.js:319 _callee2$
    [pocketworks-web]/[gatsby-plugin-advanced-sitemap]/gatsby-node.js:319:20
  
  - new Promise
  
  - gatsby-node.js:438 Object.onPostBuild
    [pocketworks-web]/[gatsby-plugin-advanced-sitemap]/gatsby-node.js:438:19
  
  - api-runner-node.js:247 runAPI
    [pocketworks-web]/[gatsby]/dist/utils/api-runner-node.js:247:41
  
  - api-runner-node.js:387 Promise.catch.pluginName
    [pocketworks-web]/[gatsby]/dist/utils/api-runner-node.js:387:13
  
  - new Promise
  
  - api-runner-node.js:386 runPlugin
    [pocketworks-web]/[gatsby]/dist/utils/api-runner-node.js:386:10
```

### Technical details:

* Gatsby Version: 2.15.30
* Node Version: v13.5.0
* OS: OSX
* gatsby-config.js: 

```
require('dotenv').config()

module.exports = {
  siteMetadata: {
    title: `Pocketworks`,
    sieUrl: 'https://pocketworks.co.uk'
  },
  plugins: [
    `gatsby-plugin-netlify`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        includePaths: ["./src"],
      }
    },
    `gatsby-transformer-remark`,
    {
      resolve: `gatsby-source-datocms`,
      options: {
        apiToken: process.env.DATO_API_TOKEN,
      },
    },
    {
      resolve: `gatsby-source-instagram`,
      options: {
        username: `pocketworks`,
      },
    },
    {
      resolve: `gatsby-plugin-hotjar`,
      options: {
        id: XXXXXXX,
        sv: 6
      },
    },    
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        // The property ID; the tracking code won't be generated without it
        trackingId: "UA-XXXXXXX-2",
        // Defines where to place the tracking script - `true` in the head and `false` in the body
        head: false,
        // Setting this parameter is optional
        anonymize: true,
        // Setting this parameter is also optional
        respectDNT: true,
        // Avoids sending pageview hits from custom paths
        exclude: [],
        // Delays sending pageview hits on route update (in milliseconds)
        pageTransitionDelay: 0,
        // // Enables Google Optimize using your container Id
        // optimizeId: "YOUR_GOOGLE_OPTIMIZE_TRACKING_ID",
        // // Enables Google Optimize Experiment ID
        // experimentId: "YOUR_GOOGLE_EXPERIMENT_ID",
        // // Set Variation ID. 0 for original 1,2,3....
        // variationId: "YOUR_GOOGLE_OPTIMIZE_VARIATION_ID",
        // // Any additional optional fields
        // sampleRate: 5,
        // siteSpeedSampleRate: 10,
        cookieDomain: "pocketworks.co.uk",
      },
    },  
    {
      resolve: "gatsby-plugin-google-tagmanager",
      options: {
        id: "GTM-XXXXXXX",
  
        // Include GTM in development.
        // Defaults to false meaning GTM will only be loaded in production.
        includeInDevelopment: false,
  
        // datalayer to be set before GTM is loaded
        // should be an object or a function that is executed in the browser
        // Defaults to null
        defaultDataLayer: { platform: "gatsby" },  
      },
    },  
    `gatsby-plugin-advanced-sitemap`
  ],
}
```

**Comment by AileenCGN** [comment] 2020-02-11 13:39
hmm.. Are you able to run this query:

```graphql
{
  allSitePage {
    edges {
      node {
        id
        slug: path
        url: path
      }
    }
  }
  site {
    siteMetadata {
      siteUrl
    }
  }
}
```

This is the default query, which will run when no query is passed. Would be good to know if that's the cause of it...

**Comment by tobinharris** [comment] 2020-02-14 20:34
Hi, thanks for the reply. Yes that gives the same error. 
```
"gatsby-plugin-advanced-sitemap" threw an error while running the onPostBuild lifecycle:

runner.query(...).then is not a function

  188 |   var query = _ref6.query,
  189 |       exclude = _ref6.exclude;
> 190 |   return handler(query).then(function (r) {
      |          ^
  191 |     if (r.errors) {
  192 |       throw new Error(r.errors.join(", "));
  193 |     }

File: node_modules/gatsby-plugin-advanced-sitemap/gatsby-node.js:190:10

  TypeError: runner.query(...).then is not a function
```
Thanks,

T

**Comment by AileenCGN** [comment] 2020-03-02 06:49
@tobinharris Can you try to run the query from above in your GraphiQL http://localhost:8000/___graphql with the sitemap plugin disabled and see, if it works?

I'm not able to reproduce this so far

**Comment by aileen** [comment] 2020-09-15 02:53
Closing this now, as I'm not able to reproduce and didn't seem to have appeared again

**Closed by aileen** 2020-09-15 02:53 UTC
